### ISSUE TITLE
catkin  build dvs_renderer errors:

### ISSUE THREAD

**Issue by uhvardhan** [uzh-rpg/rpg_dvs_ros#93]
```
--------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/kinetic
Workspace:                   /home/moca/harsh_ws
--------------------------------------------------------
Build Space:        [exists] /home/moca/harsh_ws/build
Devel Space:        [exists] /home/moca/harsh_ws/devel
Install Space:      [unused] /home/moca/harsh_ws/install
Log Space:          [exists] /home/moca/harsh_ws/logs
Source Space:       [exists] /home/moca/harsh_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        None
--------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------
[build] Found '13' packages in 0.0 seconds.                                                                                                                                                                  
[build] Package table is up to date.                                                                                                                                                                         
Starting  >>> catkin_simple                                                                                                                                                                                  
Starting  >>> cv_bridge                                                                                                                                                                                      
Finished  <<< catkin_simple                [ 0.1 seconds ]                                                                                                                                                   
Starting  >>> dvs_msgs                                                                                                                                                                                       
_____________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << dvs_msgs:make /home/moca/harsh_ws/logs/dvs_msgs/build.make.006.log                                                                                                                             
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py", line 41, in <module>
    from genmsg import EXT_MSG, EXT_SRV, MsgContext
ImportError: No module named genmsg
make[2]: *** [CMakeFiles/_dvs_msgs_generate_messages_check_deps_Event] Error 1
make[1]: *** [CMakeFiles/_dvs_msgs_generate_messages_check_deps_Event.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py", line 41, in <module>
    from genmsg import EXT_MSG, EXT_SRV, MsgContext
ImportError: No module named genmsg
make[2]: *** [CMakeFiles/_dvs_msgs_generate_messages_check_deps_EventArray] Error 1
make[1]: *** [CMakeFiles/_dvs_msgs_generate_messages_check_deps_EventArray.dir/all] Error 2
make: *** [all] Error 2
cd /home/moca/harsh_ws/build/dvs_msgs; catkin build --get-env dvs_msgs | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.............................................................................................................................................................................................................
Failed     << dvs_msgs:make                [ Exited with code 2 ]                                                                                                                                            
Failed    <<< dvs_msgs                     [ 0.1 seconds ]                                                                                                                                                   
Abandoned <<< dvs_renderer                 [ Unrelated job failed ]                                                                                                                                          
_____________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << cv_bridge:cmake /home/moca/harsh_ws/logs/cv_bridge/build.cmake.003.log                                                                                                                         
Traceback (most recent call last):
  File "/home/moca/harsh_ws/build/cv_bridge/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named catkin.environment_cache
CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python2
  "/home/moca/harsh_ws/build/cv_bridge/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/all.cmake:207 (safe_execute_process)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


cd /home/moca/harsh_ws/build/cv_bridge; catkin build --get-env cv_bridge | catkin env -si  /usr/bin/cmake /home/moca/harsh_ws/src/vision_opencv/cv_bridge --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/moca/harsh_ws/devel -DCMAKE_INSTALL_PREFIX=/home/moca/harsh_ws/install -DCMAKE_BUILD_TYPE=Release; cd -
.............................................................................................................................................................................................................
Failed     << cv_bridge:cmake              [ Exited with code 1 ]                                                                                                                                            
Failed    <<< cv_bridge                    [ 0.2 seconds ]                                                                                                                                                   
[build] Summary: 1 of 4 packages succeeded.                                                                                                                                                                  
[build]   Ignored:   9 packages were skipped or are blacklisted.                                                                                                                                             
[build]   Warnings:  None.                                                                                                                                                                                   
[build]   Abandoned: 1 packages were abandoned.                                                                                                                                                              
[build]   Failed:    2 packages failed.                                                                                                                                                                      
[build] Runtime: 0.3 seconds total. 
```

Hi, I am trying to finish the driver installation. Works great till Step 9. When I do catkin build dvs_renderer - it fails. Not really sure what to do next. 

Thanks in advance!

**Comment by guillermogb** [comment]
Googled it and found this solution: https://github.com/ros/catkin/issues/806#issuecomment-226656298
`catkin clean`
